spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  server:
    port: 8081
  prometheus:
    metrics:
      export:
        enabled: true